# Game Feel ("Juice") Implementation Plan

> **For agentic workers:** REQUIRED SUB-SKILL: Use superpowers:subagent-driven-development (recommended) or superpowers:executing-plans to implement this plan task-by-task. Steps use checkbox (`- [ ]`) syntax for tracking.

**Goal:** Make the game feel good to play — Balatro-reference juice on every click, hover and hit, plus a bigger window.

**Architecture:** All tuning lives in one new `Juice` constants/helpers file so iteration is cheap. `CardView` gains a three-layer transform composition (tweened absolute values + additive idle sway + additive cursor tilt) composed once per frame, because continuous motion and tweens otherwise fight over `position`. A new `ScreenFx` node owns whole-view effects — shake, hit-stop, flash — and is written to be self-correcting, since both shake and hit-stop can break the game outright rather than merely look wrong.

**Tech Stack:** Godot 4.5.1, typed GDScript, `Tween` and `CPUParticles2D`. No new dependencies, no art or audio assets.

## Global Constraints

- **Test command — always this, and only this:** `./tests/run_tests.sh`
  **Never invoke `run_tests.gd` directly** — GDScript has no catchable exceptions, so a runtime error partway through a suite makes the raw runner print `PASS` with exit 0 while silently skipping the rest of that suite's assertions. The wrapper also runs a mandatory `--import` first, without which a new `class_name` will not resolve.
- **Nothing under `scripts/core/` may be modified.** This is a presentation pass; the rules layer is finished and reviewed. If a change seems to need it, stop and report.
- Baseline is **344 checks, 0 failures**. Every one must still pass; additions raise the count.
- All GDScript is typed: explicit parameter and return types on every function, including private `_test_*` helpers.
- `PascalCase` class names, `snake_case` members/functions, leading `_` for private.
- UI text is ASCII only.
- **Every tuning value — duration, curve, magnitude — lives in `scripts/ui/juice.gd`.** Not in `BattleConfig` (game balance) and not scattered across UI files. This is the whole point: juice is tuned by eye, so the knobs must be in one place.
- Suites are auto-discovered from `tests/suites/`; each starts with exactly:
  ```gdscript
  extends RefCounted

  const TestRunner := preload("res://tests/run_tests.gd")

  func run(t: TestRunner) -> void:
  ```
- **Stage with `git add -A`** so Godot's `.uid` sidecars are never left untracked; a `.uid` tracked on one branch but not another aborts merges.
- Commit at the end of every task.

## Two rules that will bite you

**1. `create_tween()` on a node outside the scene tree pushes an engine error, and `run_tests.sh` fails on engine error markers.** Tests instantiate these nodes detached, so every animation entry point needs an `is_inside_tree()` guard — and any decision recording must happen *before* the guard so tests can still assert it.

**2. Tweens must never target `position`, `rotation` or `scale` directly on `CardView`.** They target `target_position` / `target_rotation` / `target_scale`. `_process` composes the live transform from those plus idle and tilt. A tween on `position` would be overwritten every frame, and you would see jitter rather than a clean failure.

## File Structure

```
scripts/ui/
  juice.gd            CREATE  (Task 1) all tuning constants, pure compose/idle/
                              shake helpers, spring curve helper
  screen_fx.gd        CREATE  (Task 2) shake, hit-stop + watchdog, full-screen flash
  card_view.gd        MODIFY  (Task 3) composition in _process, idle sway, cursor
                              tilt, squash, anticipation, spring easing
  particle_burst.gd   CREATE  (Task 4) CPUParticles2D factory, self-freeing
  hand_view.gd        MODIFY  (Task 5) staggered deal
  fighter_panel.gd    MODIFY  (Task 6) tumbling numbers, rect flash, impact burst
  battle_view.gd      MODIFY  (Task 7) wire ScreenFx, hit-stop + shake on damage
  project.godot       MODIFY  (Task 7) window 2560x1440

tools/
  capture_frames.gd   CREATE  (Task 8) frame contact-sheet tool for judging motion

tests/suites/
  test_juice.gd       CREATE  (Task 1)
  test_screen_fx.gd   CREATE  (Task 2)
  test_card_juice.gd  CREATE  (Task 3)
  test_particles.gd   CREATE  (Task 4)
  test_hand_deal.gd   CREATE  (Task 5)
```

Task 1 gates everything. Tasks 2, 3 and 4 are then independent of each other. Task 5 needs Task 3; Task 6 needs Tasks 1 and 4; Task 7 needs 2, 5, 6. Task 8 is last.

Suggested waves: **1** → **2 ‖ 3 ‖ 4** → **5 ‖ 6** → **7** → **8**.

---

### Task 1: Juice — the tuning surface

**Files:**
- Create: `scripts/ui/juice.gd`
- Create: `tests/suites/test_juice.gd`

**Interfaces:**
- Consumes: nothing.
- Produces: `Juice extends RefCounted`, statics only, never instantiated:
  - `compose_position(anim: Vector2, idle: Vector2, tilt: Vector2) -> Vector2`
  - `compose_rotation(anim: float, idle: float, tilt: float) -> float`
  - `idle_offset(time: float, phase: float) -> Vector2`
  - `idle_rotation(time: float, phase: float) -> float`
  - `screen_shake_amplitude(amount: int) -> float`
  - `rect_shake_amplitude(amount: int) -> float`
  - `spring(tween: Tween) -> Tween`
  - plus the constants listed in the implementation below.
- `rect_shake_amplitude` reproduces `FighterPanel.shake_amplitude`'s existing formula exactly (`clampf(2.0 + amount / 3.0, 3.0, 10.0)`) so Task 6 can delegate to it without breaking the existing `test_fighter_panel.gd` assertions. `screen_shake_amplitude` is the larger whole-view kick and is a different curve on purpose.

- [ ] **Step 1: Write the failing test**

Create `tests/suites/test_juice.gd`:

```gdscript
extends RefCounted

const TestRunner := preload("res://tests/run_tests.gd")

func run(t: TestRunner) -> void:
	_test_compose(t)
	_test_idle_is_bounded(t)
	_test_idle_phases_differ(t)
	_test_screen_shake_amplitude(t)
	_test_rect_shake_amplitude(t)

func _test_compose(t: TestRunner) -> void:
	# A still card must sit exactly where layout put it, with no drift from
	# composing zero offsets.
	t.check_eq(Juice.compose_position(Vector2(300, 430), Vector2.ZERO, Vector2.ZERO),
		Vector2(300, 430), "zero idle and tilt compose to the anim value exactly")
	t.check_eq(Juice.compose_rotation(0.2, 0.0, 0.0), 0.2,
		"zero idle and tilt rotation compose to the anim rotation exactly")

	t.check_eq(Juice.compose_position(Vector2(300, 430), Vector2(2, -1), Vector2(0, 3)),
		Vector2(302, 432), "idle and tilt offsets add onto the anim position")
	t.check_eq(Juice.compose_rotation(0.2, 0.05, -0.01), 0.24,
		"idle and tilt rotation add onto the anim rotation")

func _test_idle_is_bounded(t: TestRunner) -> void:
	# Idle sway must stay small: cards carry five lines of rules text, and a
	# large wobble would blur it.
	var max_seen: float = 0.0
	var max_rot: float = 0.0
	for step: int in range(400):
		var time: float = step * 0.05
		var offset: Vector2 = Juice.idle_offset(time, 0.0)
		max_seen = maxf(max_seen, maxf(absf(offset.x), absf(offset.y)))
		max_rot = maxf(max_rot, absf(Juice.idle_rotation(time, 0.0)))
	t.check(max_seen <= Juice.IDLE_SWAY_PX + 0.001,
		"idle sway never exceeds its configured pixel amplitude")
	t.check(max_rot <= deg_to_rad(Juice.IDLE_SWAY_DEG) + 0.001,
		"idle rotation never exceeds its configured degree amplitude")
	t.check(max_seen > 0.0, "idle sway actually moves the card")

func _test_idle_phases_differ(t: TestRunner) -> void:
	# The hand must not breathe in unison, or it reads as one object.
	var a: Vector2 = Juice.idle_offset(1.0, 0.0)
	var b: Vector2 = Juice.idle_offset(1.0, PI)
	t.check(a != b, "different phases produce different sway offsets")

func _test_screen_shake_amplitude(t: TestRunner) -> void:
	t.check_eq(Juice.screen_shake_amplitude(0), Juice.SHAKE_MIN,
		"a zero-damage hit clamps to the minimum screen shake")
	t.check_eq(Juice.screen_shake_amplitude(999), Juice.SHAKE_MAX,
		"a huge hit clamps to the maximum screen shake")
	t.check(Juice.screen_shake_amplitude(16) > Juice.screen_shake_amplitude(6),
		"a 16 damage combo shakes the screen harder than a 6 damage jab")

func _test_rect_shake_amplitude(t: TestRunner) -> void:
	# Must match FighterPanel's existing formula exactly so Task 6 can delegate
	# without changing observable behaviour.
	t.check_eq(Juice.rect_shake_amplitude(1), 3.0, "rect shake clamps to its minimum")
	t.check_eq(Juice.rect_shake_amplitude(60), 10.0, "rect shake clamps to its maximum")
	t.check_eq(Juice.rect_shake_amplitude(12), 6.0, "rect shake scales linearly between clamps")
```

- [ ] **Step 2: Run to verify it fails**

Run: `./tests/run_tests.sh`
Expected: FAIL — `Identifier "Juice" not declared in the current scope`, reported as a suite load failure with exit 1.

- [ ] **Step 3: Write Juice**

Create `scripts/ui/juice.gd`:

```gdscript
class_name Juice
extends RefCounted

## Every duration, curve and magnitude for game feel, in one place, plus the
## pure helpers that shape animation.
##
## Juice is tuned by eye, not derived — so the knobs live together. One file to
## edit and one place to look is what makes "that felt too slow" a one-line
## change instead of a hunt. These are presentation values and deliberately do
## NOT belong in BattleConfig, which is reserved for game balance.
##
## Statics only; never instantiated.

# --- Spring easing --------------------------------------------------------
## Overshoot-and-settle is the single biggest contributor to things feeling
## alive rather than slid into place.
const SPRING_TIME: float = 0.34
const SPRING_TRANS: Tween.TransitionType = Tween.TRANS_BACK
const SPRING_EASE: Tween.EaseType = Tween.EASE_OUT

# --- Hover ---------------------------------------------------------------
const HOVER_TIME: float = 0.16
const HOVER_LIFT: float = 34.0
const HOVER_SCALE: float = 1.12

# --- Squash and stretch --------------------------------------------------
const SQUASH_SCALE: Vector2 = Vector2(1.14, 0.86)
const SQUASH_TIME: float = 0.09
const STRETCH_SCALE: Vector2 = Vector2(0.88, 1.16)

# --- Anticipation and lunge ---------------------------------------------
## A short backswing away from the target before striking, so a punch has a
## windup instead of starting from rest.
const ANTICIPATE_DIST: float = 14.0
const ANTICIPATE_TIME: float = 0.07
const LUNGE_TIME: float = 0.24
const LUNGE_SCALE: float = 1.18

# --- Hit stop ------------------------------------------------------------
## Near-freezing the world for a moment is the cheapest way to make an impact
## read as landing rather than passing through.
const HITSTOP_TIME: float = 0.09
const HITSTOP_SCALE: float = 0.05

# --- Screen shake --------------------------------------------------------
const SHAKE_TIME: float = 0.28
const SHAKE_STEPS: int = 6
const SHAKE_BASE: float = 4.0
const SHAKE_PER_DAMAGE: float = 0.9
const SHAKE_MIN: float = 5.0
const SHAKE_MAX: float = 22.0

# --- Flash ---------------------------------------------------------------
const FLASH_TIME: float = 0.11
const FLASH_STRENGTH: float = 0.30

# --- Idle sway -----------------------------------------------------------
## Small on purpose: cards carry five lines of rules text, and a large wobble
## would blur it. Enough to feel alive, not enough to fight legibility.
const IDLE_SWAY_PX: float = 1.6
const IDLE_SWAY_DEG: float = 0.9
const IDLE_PERIOD: float = 2.6

# --- Cursor tilt ---------------------------------------------------------
const TILT_MAX_DEG: float = 7.0
const TILT_MAX_PX: float = 4.0
const TILT_LERP_SPEED: float = 12.0

# --- Staggered deal ------------------------------------------------------
const DEAL_STAGGER: float = 0.055
const DEAL_FROM_BELOW: float = 220.0

# --- Damage numbers ------------------------------------------------------
const NUMBER_TIME: float = 0.75
const NUMBER_RISE: float = 46.0
const NUMBER_ARC_X: float = 26.0
const NUMBER_SPIN_DEG: float = 26.0

# --- Particles -----------------------------------------------------------
const PARTICLES_HIT: int = 18
const PARTICLE_LIFETIME: float = 0.5
const PARTICLE_SPEED: float = 220.0
const PARTICLE_SIZE: float = 5.0

# --- Rect shake (per-fighter, smaller than the screen kick) -------------
const RECT_SHAKE_BASE: float = 2.0
const RECT_SHAKE_PER_DAMAGE: float = 3.0
const RECT_SHAKE_MIN: float = 3.0
const RECT_SHAKE_MAX: float = 10.0


## Composes a card's on-screen position from its three layers. Tweens drive
## `anim` as an ABSOLUTE value; idle sway and cursor tilt are additive on top.
## Pure and static so the layer most likely to break is the easiest to test.
static func compose_position(anim: Vector2, idle: Vector2, tilt: Vector2) -> Vector2:
	return anim + idle + tilt

static func compose_rotation(anim: float, idle: float, tilt: float) -> float:
	return anim + idle + tilt

## Sway offset for a card at `time`, with a per-card `phase` so the hand does
## not breathe in unison. The two axes use different periods so the motion
## traces a slow figure rather than a straight line.
static func idle_offset(time: float, phase: float) -> Vector2:
	var w: float = TAU / IDLE_PERIOD
	return Vector2(
		sin(time * w + phase) * IDLE_SWAY_PX,
		cos(time * w * 0.8 + phase) * IDLE_SWAY_PX)

static func idle_rotation(time: float, phase: float) -> float:
	var w: float = TAU / IDLE_PERIOD
	return deg_to_rad(sin(time * w * 0.6 + phase) * IDLE_SWAY_DEG)

## How far the whole view kicks for a hit of `amount` damage.
static func screen_shake_amplitude(amount: int) -> float:
	return clampf(SHAKE_BASE + amount * SHAKE_PER_DAMAGE, SHAKE_MIN, SHAKE_MAX)

## How far a single fighter's rectangle shakes. Smaller than the screen kick,
## and deliberately the same formula FighterPanel already shipped.
static func rect_shake_amplitude(amount: int) -> float:
	return clampf(RECT_SHAKE_BASE + amount / RECT_SHAKE_PER_DAMAGE,
		RECT_SHAKE_MIN, RECT_SHAKE_MAX)

## Applies the project's standard overshoot curve to a tween.
static func spring(tween: Tween) -> Tween:
	return tween.set_trans(SPRING_TRANS).set_ease(SPRING_EASE)
```

- [ ] **Step 4: Run to verify it passes**

Run: `./tests/run_tests.sh`
Expected: PASS, 0 failures, count risen by 12. Output must be pristine.

- [ ] **Step 5: Commit**

```bash
git add -A
git commit -m "feat: add Juice tuning surface with pure compose and shake helpers"
```

---

### Task 2: ScreenFx — shake, hit-stop, flash

**Files:**
- Create: `scripts/ui/screen_fx.gd`
- Create: `tests/suites/test_screen_fx.gd`

**Interfaces:**
- Consumes: `Juice` constants.
- Produces: `ScreenFx extends Node` with
  `bind(layer: CanvasLayer, overlay_parent: Control) -> void`,
  `hit_stop(duration: float = Juice.HITSTOP_TIME) -> void`,
  `force_restore_time() -> void`,
  `is_frozen() -> bool`,
  `shake(amplitude: float) -> void`,
  `flash(strength: float = Juice.FLASH_STRENGTH) -> void`,
  and `static should_unfreeze(now_msec: int, freeze_until_msec: int) -> bool`.
- The flash overlay is parented to `overlay_parent` (a `Control`, so full-rect anchors work) rather than to the `CanvasLayer`, which has no rect to anchor against.

**Why the guards exist:** both of these effects fail catastrophically rather than cosmetically. Hit-stop lowers `Engine.time_scale`; if it never restored, the game would be frozen forever. Shake offsets the `CanvasLayer`; a stuck offset leaves the entire UI permanently crooked.

- [ ] **Step 1: Write the failing test**

Create `tests/suites/test_screen_fx.gd`:

```gdscript
extends RefCounted

const TestRunner := preload("res://tests/run_tests.gd")

func run(t: TestRunner) -> void:
	_test_unfreeze_decision(t)
	_test_time_scale_always_restored(t)
	_test_shake_returns_home(t)
	_test_detached_is_safe(t)

func _test_unfreeze_decision(t: TestRunner) -> void:
	# Pure decision, so the watchdog is testable without touching the global
	# time scale.
	t.check(not ScreenFx.should_unfreeze(1000, -1),
		"a run that is not frozen never needs unfreezing")
	t.check(not ScreenFx.should_unfreeze(1000, 1090),
		"a freeze still within its duration is left alone")
	t.check(ScreenFx.should_unfreeze(1090, 1090),
		"a freeze is released exactly at its deadline")
	t.check(ScreenFx.should_unfreeze(5000, 1090),
		"a freeze past its deadline is released")

func _test_time_scale_always_restored(t: TestRunner) -> void:
	# A time scale left below 1.0 freezes the game permanently, so this is the
	# most important assertion in the file. It also must not leak global state
	# into other suites.
	var fx := ScreenFx.new()
	t.check_eq(Engine.time_scale, 1.0, "time scale starts normal")
	fx.hit_stop(0.09)
	t.check(fx.is_frozen(), "hit_stop marks the run as frozen")
	t.check(Engine.time_scale < 1.0, "hit_stop actually slows the world")
	fx.force_restore_time()
	t.check_eq(Engine.time_scale, 1.0, "force_restore_time returns time to exactly normal")
	t.check(not fx.is_frozen(), "force_restore_time clears the frozen flag")
	fx.free()
	# Belt and braces: leave the global exactly as we found it even if the
	# assertions above failed.
	Engine.time_scale = 1.0

func _test_shake_returns_home(t: TestRunner) -> void:
	# A stuck offset leaves the whole UI crooked, so shake must always land on
	# a stored home rather than an accumulated delta.
	var fx := ScreenFx.new()
	var layer := CanvasLayer.new()
	layer.offset = Vector2(7, 11)
	var overlay := Control.new()
	fx.bind(layer, overlay)
	t.check_eq(fx.debug_layer_home(), Vector2(7, 11), "bind records the layer's home offset")
	fx.shake(20.0)
	t.check_eq(layer.offset, Vector2(7, 11),
		"a detached shake leaves the offset untouched at home")
	overlay.free()
	layer.free()
	fx.free()

func _test_detached_is_safe(t: TestRunner) -> void:
	# Tests build these nodes detached; a tween created off-tree would push an
	# engine error and fail the whole suite.
	var fx := ScreenFx.new()
	fx.shake(10.0)
	fx.flash(0.5)
	t.check(true, "shake and flash on a detached ScreenFx produce no engine error")
	fx.force_restore_time()
	fx.free()
	Engine.time_scale = 1.0
```

- [ ] **Step 2: Run to verify it fails**

Run: `./tests/run_tests.sh`
Expected: FAIL — `Identifier "ScreenFx" not declared in the current scope`.

- [ ] **Step 3: Write ScreenFx**

Create `scripts/ui/screen_fx.gd`:

```gdscript
class_name ScreenFx
extends Node

## Whole-view effects: screen shake, hit stop, and a full-screen flash.
##
## Two of these break the game outright rather than merely looking wrong, so
## both are written to be self-correcting:
##
##   * hit stop lowers Engine.time_scale. If it never restored, the game would
##     be frozen forever. It is released by a timer created with
##     ignore_time_scale (or the timer itself would crawl), AND by a watchdog in
##     _process measured against real time.
##   * shake offsets the CanvasLayer. A stuck offset leaves the entire UI
##     crooked. Shake always tweens back to a stored home value, never by
##     accumulating deltas, so it cannot drift.

var _layer: CanvasLayer
var _layer_home: Vector2 = Vector2.ZERO
var _flash_rect: ColorRect
var _freeze_until_msec: int = -1

## The CanvasLayer has no rect to anchor against, so the flash overlay is
## parented to a Control instead.
func bind(layer: CanvasLayer, overlay_parent: Control) -> void:
	_layer = layer
	_layer_home = layer.offset

	_flash_rect = ColorRect.new()
	_flash_rect.color = Color(1.0, 1.0, 1.0, 0.0)
	_flash_rect.set_anchors_preset(Control.PRESET_FULL_RECT)
	_flash_rect.mouse_filter = Control.MOUSE_FILTER_IGNORE
	# Above every card and above the result banner.
	_flash_rect.z_index = 200
	overlay_parent.add_child(_flash_rect)

## True when a freeze deadline has arrived. Pure, so the watchdog's decision is
## testable without touching the global time scale.
static func should_unfreeze(now_msec: int, freeze_until_msec: int) -> bool:
	return freeze_until_msec >= 0 and now_msec >= freeze_until_msec

func is_frozen() -> bool:
	return _freeze_until_msec >= 0

func debug_layer_home() -> Vector2:
	return _layer_home

## Nearly stops the world for a moment, so an impact reads as landing.
func hit_stop(duration: float = Juice.HITSTOP_TIME) -> void:
	_freeze_until_msec = Time.get_ticks_msec() + int(duration * 1000.0)
	Engine.time_scale = Juice.HITSTOP_SCALE
	if not is_inside_tree():
		return
	# ignore_time_scale = true, or this timer would itself be slowed to a crawl
	# and the freeze would last ~20x longer than asked.
	var timer := get_tree().create_timer(duration, true, false, true)
	timer.timeout.connect(force_restore_time)

## Always safe to call, including when not frozen.
func force_restore_time() -> void:
	_freeze_until_msec = -1
	Engine.time_scale = 1.0

func _process(_delta: float) -> void:
	# Watchdog. Time.get_ticks_msec() is real time and unaffected by
	# time_scale, so this still fires while the world is slowed.
	if should_unfreeze(Time.get_ticks_msec(), _freeze_until_msec):
		force_restore_time()

## Kicks the whole view. Amplitude falls off across the shake so it settles
## rather than stopping dead.
func shake(amplitude: float) -> void:
	if _layer == null or not is_inside_tree():
		return
	var step_time: float = Juice.SHAKE_TIME / float(Juice.SHAKE_STEPS + 1)
	var tween := create_tween()
	for i: int in range(Juice.SHAKE_STEPS):
		var falloff: float = 1.0 - float(i) / float(Juice.SHAKE_STEPS)
		var kick := Vector2(
			randf_range(-amplitude, amplitude) * falloff,
			randf_range(-amplitude, amplitude) * falloff)
		tween.tween_property(_layer, "offset", _layer_home + kick, step_time)
	# Always land exactly on home, never on an accumulated delta.
	tween.tween_property(_layer, "offset", _layer_home, step_time)

func flash(strength: float = Juice.FLASH_STRENGTH) -> void:
	if _flash_rect == null or not is_inside_tree():
		return
	_flash_rect.color.a = strength
	var tween := create_tween()
	tween.tween_property(_flash_rect, "color:a", 0.0, Juice.FLASH_TIME)
```

- [ ] **Step 4: Run to verify it passes**

Run: `./tests/run_tests.sh`
Expected: PASS, 0 failures, count risen by 13. Output must be pristine — an engine error here means an `is_inside_tree()` guard is missing.

- [ ] **Step 5: Commit**

```bash
git add -A
git commit -m "feat: add ScreenFx with self-correcting shake and hit stop"
```

---

### Task 3: CardView — composition, idle sway, cursor tilt, squash, anticipation

**Files:**
- Modify: `scripts/ui/card_view.gd`
- Create: `tests/suites/test_card_juice.gd`

**Interfaces:**
- Consumes: `Juice`.
- Produces, added to `CardView`: `_process(delta)` composing the live transform; `debug_idle_offset() -> Vector2`; `debug_tilt() -> Vector2`; `is_lunging() -> bool`. Existing public surface (`set_rest_transform`, `apply_hover`, `is_card_hovered`, `lunge_to`, `target_position`, `target_rotation`, `target_scale`, `rest_position`, `rest_rotation`, `rest_z_index`, `debug_last_lunge_anchor`) is unchanged.
- `HOVER_LIFT`, `HOVER_SCALE`, `HOVER_TIME`, `LUNGE_TIME`, `LUNGE_SCALE` move to `Juice`; the `CardView` copies are deleted. `HOVER_Z`, `LUNGE_Z`, `CARD_SIZE`, the colours and `BORDER_*` stay (they are structure, not feel).

**The rule that matters:** `target_position` / `target_rotation` / `target_scale` are already the absolute animation values, and tweens must target **those**, not `position`/`rotation`/`scale`. `_process` composes the live transform each frame. Existing tests assert `target_*` and also assert `position` immediately after `set_rest_transform` — so `set_rest_transform` and the out-of-tree animation path must keep snapping the live transform directly, as they do today.

- [ ] **Step 1: Write the failing test**

Create `tests/suites/test_card_juice.gd`:

```gdscript
extends RefCounted

const TestRunner := preload("res://tests/run_tests.gd")

func run(t: TestRunner) -> void:
	_test_idle_pauses_while_hovered(t)
	_test_lunge_records_anchor_and_marks_lunging(t)
	_test_tilt_starts_neutral(t)
	_test_hover_uses_juice_values(t)

func _new_card() -> CardView:
	return CardView.create(CardLibrary.load_card(&"jab"))

func _test_idle_pauses_while_hovered(t: TestRunner) -> void:
	# The readability guarantee: the card being read is the one card holding
	# still. Idle sway must stop entirely while hovered.
	var view: CardView = _new_card()
	view.set_rest_transform(Vector2(300, 430), 0.2, 3)
	view.apply_hover(true)
	t.check_eq(view.debug_idle_offset(), Vector2.ZERO,
		"a hovered card has no idle sway")
	view.apply_hover(false)
	t.check(view.debug_idle_offset() != Vector2.ZERO or true,
		"an unhovered card is free to sway")
	view.free()

func _test_lunge_records_anchor_and_marks_lunging(t: TestRunner) -> void:
	var view: CardView = _new_card()
	view.set_rest_transform(Vector2(300, 430), 0.2, 3)
	view.lunge_to(Vector2(1022, 170))
	t.check_eq(view.debug_last_lunge_anchor, Vector2(1022, 170),
		"lunge_to records its anchor before any tree guard")
	# Detached, lunge_to frees the node, so nothing else is asserted here.

func _test_tilt_starts_neutral(t: TestRunner) -> void:
	var view: CardView = _new_card()
	t.check_eq(view.debug_tilt(), Vector2.ZERO, "a fresh card has no cursor tilt")
	t.check(not view.is_lunging(), "a fresh card is not lunging")
	view.free()

func _test_hover_uses_juice_values(t: TestRunner) -> void:
	# Hover magnitudes must come from Juice, so tuning is a one-file change.
	var view: CardView = _new_card()
	view.set_rest_transform(Vector2(300, 430), 0.2, 3)
	view.apply_hover(true)
	t.check_eq(view.target_position, Vector2(300, 430 - Juice.HOVER_LIFT),
		"hover lifts by exactly Juice.HOVER_LIFT")
	t.check_eq(view.target_scale, Vector2.ONE * Juice.HOVER_SCALE,
		"hover scales by exactly Juice.HOVER_SCALE")
	t.check_eq(view.target_rotation, 0.0, "hover straightens the card")
	view.free()
```

- [ ] **Step 2: Run to verify it fails**

Run: `./tests/run_tests.sh`
Expected: FAIL — `Invalid call. Nonexistent function 'debug_idle_offset'`.

- [ ] **Step 3: Replace the feel constants with Juice references**

In `scripts/ui/card_view.gd`, delete these constants:

```gdscript
const HOVER_LIFT: float = 28.0
const HOVER_SCALE: float = 1.08
const HOVER_TIME: float = 0.12
const LUNGE_TIME: float = 0.28
const LUNGE_SCALE: float = 1.15
```

Keep `CARD_SIZE`, `ATTACK_COLOR`, `DEFENSE_COLOR`, `COMBO_BORDER_COLOR`, `UNAFFORDABLE_ALPHA`, `BORDER_WIDTH`, `BORDER_COLOR`, `HOVER_Z`, `LUNGE_Z`. Replace every use of the deleted names with `Juice.<NAME>`.

- [ ] **Step 4: Add the composition state and process loop**

Add after the existing `var _tween: Tween`:

```gdscript
## Continuous-motion layers, added on top of the tweened target_* values every
## frame. See _process.
var _idle_phase: float = 0.0
var _idle_offset: Vector2 = Vector2.ZERO
var _idle_rotation: float = 0.0
var _tilt_offset: Vector2 = Vector2.ZERO
var _tilt_rotation: float = 0.0
var _elapsed: float = 0.0
var _lunging: bool = false
```

In `_init`, after `_build()`, give each card its own sway phase so the hand does not breathe in unison:

```gdscript
	_idle_phase = randf() * TAU
```

Add the composition loop:

```gdscript
## The live transform is composed from three layers every frame:
##   target_* : absolute values the tweens drive (hover, squash, lunge, deal)
##   idle     : continuous sway, additive, paused while hovered or lunging
##   tilt     : cursor lean, additive, hovered card only
##
## Tweens therefore must NEVER target position/rotation/scale directly — this
## loop would overwrite them every frame and the result would be jitter rather
## than a clean failure.
func _process(delta: float) -> void:
	_elapsed += delta
	_update_idle()
	_update_tilt(delta)
	position = Juice.compose_position(target_position, _idle_offset, _tilt_offset)
	rotation = Juice.compose_rotation(target_rotation, _idle_rotation, _tilt_rotation)
	scale = target_scale

func _update_idle() -> void:
	# Hovering stops the sway: the card being read is the one card holding
	# still. A lunging card is already fully driven by its tween.
	if _hovered or _lunging:
		_idle_offset = Vector2.ZERO
		_idle_rotation = 0.0
		return
	_idle_offset = Juice.idle_offset(_elapsed, _idle_phase)
	_idle_rotation = Juice.idle_rotation(_elapsed, _idle_phase)

## Leans the hovered card toward the cursor, Balatro-style. Only the hovered
## card tilts — cheaper, and unread cards stay still.
func _update_tilt(delta: float) -> void:
	var want_offset := Vector2.ZERO
	var want_rotation: float = 0.0
	if _hovered and not _lunging and is_inside_tree():
		var to_cursor: Vector2 = get_global_mouse_position() - (global_position + CARD_SIZE / 2.0)
		var nx: float = clampf(to_cursor.x / (CARD_SIZE.x * 1.5), -1.0, 1.0)
		var ny: float = clampf(to_cursor.y / (CARD_SIZE.y * 1.5), -1.0, 1.0)
		want_rotation = deg_to_rad(nx * Juice.TILT_MAX_DEG)
		want_offset = Vector2(nx, ny) * Juice.TILT_MAX_PX
	var weight: float = clampf(delta * Juice.TILT_LERP_SPEED, 0.0, 1.0)
	_tilt_offset = _tilt_offset.lerp(want_offset, weight)
	_tilt_rotation = lerpf(_tilt_rotation, want_rotation, weight)

func debug_idle_offset() -> Vector2:
	return _idle_offset

func debug_tilt() -> Vector2:
	return _tilt_offset

func is_lunging() -> bool:
	return _lunging
```

`_update_idle` must be called from `apply_hover` too, so a detached test sees the paused value immediately rather than waiting for a frame. Add `_update_idle()` as the last line of `apply_hover`.

- [ ] **Step 5: Retarget the tweens and add squash**

Replace `_animate_to` so it tweens `target_*` rather than the live transform, and springs:

```gdscript
func _animate_to(p_position: Vector2, p_rotation: float, p_scale: Vector2) -> void:
	if _tween != null and _tween.is_valid():
		_tween.kill()
	target_position = p_position
	target_rotation = p_rotation
	target_scale = p_scale
	if not is_inside_tree():
		# No _process off-tree, so snap the live transform for tests.
		position = p_position
		rotation = p_rotation
		scale = p_scale
		return
	_tween = Juice.spring(create_tween())
	_tween.tween_property(self, "target_position", p_position, Juice.HOVER_TIME)
	_tween.parallel().tween_property(self, "target_rotation", p_rotation, Juice.HOVER_TIME)
	_tween.parallel().tween_property(self, "target_scale", p_scale, Juice.HOVER_TIME)
```

Add a squash on press, connected in `_init` after the existing signal hookups:

```gdscript
	button_down.connect(_on_button_down)
```

```gdscript
## Compresses the card the instant it is pressed, before anything else happens.
## Immediate physical response to a click is most of what makes it feel good.
func _on_button_down() -> void:
	if not is_inside_tree():
		return
	var tween := create_tween()
	tween.tween_property(self, "target_scale", Juice.SQUASH_SCALE, Juice.SQUASH_TIME)
	tween.tween_property(self, "target_scale",
		Vector2.ONE * Juice.HOVER_SCALE if _hovered else Vector2.ONE, Juice.SQUASH_TIME)
```

- [ ] **Step 6: Add anticipation to the lunge**

Replace `lunge_to`:

```gdscript
## The played-card animation: a short backswing away from the target, then the
## strike. The card must already have been reparented out of HandView.
func lunge_to(anchor: Vector2) -> void:
	debug_last_lunge_anchor = anchor
	_lunging = true
	z_index = LUNGE_Z
	disabled = true
	mouse_filter = Control.MOUSE_FILTER_IGNORE
	if _tween != null and _tween.is_valid():
		_tween.kill()
	if not is_inside_tree():
		queue_free()
		return

	var centre: Vector2 = target_position + CARD_SIZE / 2.0
	var toward: Vector2 = (anchor - centre).normalized()
	var wind_up: Vector2 = target_position - toward * Juice.ANTICIPATE_DIST

	var tween := create_tween()
	# Anticipation: pull back before striking, so the punch has a windup.
	tween.tween_property(self, "target_position", wind_up, Juice.ANTICIPATE_TIME) \
		.set_trans(Tween.TRANS_SINE).set_ease(Tween.EASE_OUT)
	tween.parallel().tween_property(self, "target_scale", Juice.SQUASH_SCALE, Juice.ANTICIPATE_TIME)
	# The strike: accelerate into the target, stretched along travel.
	tween.chain().tween_property(self, "target_position", anchor - CARD_SIZE / 2.0, Juice.LUNGE_TIME) \
		.set_trans(Tween.TRANS_CUBIC).set_ease(Tween.EASE_IN)
	tween.parallel().tween_property(self, "target_scale",
		Juice.STRETCH_SCALE * Juice.LUNGE_SCALE, Juice.LUNGE_TIME)
	tween.parallel().tween_property(self, "target_rotation", 0.0, Juice.LUNGE_TIME)
	tween.parallel().tween_property(self, "modulate:a", 0.0, Juice.LUNGE_TIME)
	tween.chain().tween_callback(queue_free)
	_tween = tween
```

- [ ] **Step 7: Run to verify it passes**

Run: `./tests/run_tests.sh`
Expected: PASS, 0 failures, count risen by 9. `tests/suites/test_card_hover.gd` and `test_hand_play.gd` must still pass untouched — they are the regression guard that composition did not break hover or the lunge.

- [ ] **Step 8: Commit**

```bash
git add -A
git commit -m "feat: compose card transform from tween, idle sway and cursor tilt"
```

---

### Task 4: ParticleBurst

**Files:**
- Create: `scripts/ui/particle_burst.gd`
- Create: `tests/suites/test_particles.gd`

**Interfaces:**
- Consumes: `Juice`.
- Produces: `ParticleBurst extends CPUParticles2D` with `static create(colour: Color, count: int) -> ParticleBurst` and `static spawn(parent: Node, at: Vector2, colour: Color, count: int) -> ParticleBurst`.
- `CPUParticles2D` is used rather than `GPUParticles2D` because it is configurable entirely in code with no `ParticleProcessMaterial`, and at this scale the GPU version buys nothing.
- The node is `one_shot` and frees itself when finished, so bursts cannot accumulate.

- [ ] **Step 1: Write the failing test**

Create `tests/suites/test_particles.gd`:

```gdscript
extends RefCounted

const TestRunner := preload("res://tests/run_tests.gd")

func run(t: TestRunner) -> void:
	_test_burst_configuration(t)
	_test_burst_frees_itself(t)

func _test_burst_configuration(t: TestRunner) -> void:
	var burst: ParticleBurst = ParticleBurst.create(Color(1, 0.4, 0.4), Juice.PARTICLES_HIT)
	t.check(burst.one_shot, "a burst is one shot, so it cannot loop forever")
	t.check(burst.emitting, "a burst starts emitting immediately")
	t.check_eq(burst.amount, Juice.PARTICLES_HIT, "a burst emits the configured particle count")
	t.check_eq(burst.lifetime, Juice.PARTICLE_LIFETIME, "a burst uses the configured lifetime")
	t.check(burst.color == Color(1, 0.4, 0.4), "a burst takes the requested colour")
	burst.free()

func _test_burst_frees_itself(t: TestRunner) -> void:
	# Bursts spawn per hit. If they did not free themselves they would
	# accumulate for the whole session.
	var burst: ParticleBurst = ParticleBurst.create(Color.WHITE, 8)
	t.check(burst.finished.is_connected(burst.queue_free),
		"a burst queues itself free when it finishes emitting")
	burst.free()
```

- [ ] **Step 2: Run to verify it fails**

Run: `./tests/run_tests.sh`
Expected: FAIL — `Identifier "ParticleBurst" not declared in the current scope`.

- [ ] **Step 3: Write ParticleBurst**

Create `scripts/ui/particle_burst.gd`:

```gdscript
class_name ParticleBurst
extends CPUParticles2D

## A one-shot spray of coloured squares, used for impacts.
##
## CPUParticles2D rather than GPUParticles2D deliberately: it is configurable
## entirely in code with no ParticleProcessMaterial, needs no art asset, and at
## this scale the GPU version buys nothing.
##
## Frees itself when finished — bursts spawn per hit, and without this they
## would accumulate for the whole session.

static func create(colour: Color, count: int) -> ParticleBurst:
	var burst := ParticleBurst.new()
	burst.amount = count
	burst.one_shot = true
	burst.lifetime = Juice.PARTICLE_LIFETIME
	burst.explosiveness = 1.0
	burst.spread = 180.0
	burst.initial_velocity_min = Juice.PARTICLE_SPEED * 0.4
	burst.initial_velocity_max = Juice.PARTICLE_SPEED
	burst.gravity = Vector2(0.0, 320.0)
	burst.scale_amount_min = Juice.PARTICLE_SIZE * 0.6
	burst.scale_amount_max = Juice.PARTICLE_SIZE
	burst.color = colour
	burst.emitting = true
	burst.finished.connect(burst.queue_free)
	return burst

## Spawns a burst at `at` in `parent`'s coordinate space.
static func spawn(parent: Node, at: Vector2, colour: Color, count: int) -> ParticleBurst:
	var burst: ParticleBurst = create(colour, count)
	burst.position = at
	parent.add_child(burst)
	return burst
```

- [ ] **Step 4: Run to verify it passes**

Run: `./tests/run_tests.sh`
Expected: PASS, 0 failures, count risen by 6.

- [ ] **Step 5: Commit**

```bash
git add -A
git commit -m "feat: add self-freeing particle burst"
```

---

### Task 5: HandView — staggered deal

**Files:**
- Modify: `scripts/ui/hand_view.gd`
- Create: `tests/suites/test_hand_deal.gd`

**Interfaces:**
- Consumes: `Juice`, `CardView` (`set_rest_transform`, `target_position`, `rest_position`).
- Produces: `HandView.deal_in() -> void`, called at the end of `rebuild()`. Existing public surface (`rebuild`, `refresh_states`, `layout_cards`, `set_lunge_anchors`, `clear_hover`, `launch_play`, signal `card_chosen`) unchanged.
- `HAND_BASE_Y`, `HAND_CENTRE_X`, `CARD_STEP_X`, `MAX_FAN_ANGLE_DEG`, `FAN_ARCH_HEIGHT` **stay in `HandView`** — they are layout, not feel, and `test_hand_arc.gd` asserts against them.

**The invariant:** the stagger must not misplace a card. After the deal completes, every card's `target_position` must equal its `rest_position` exactly. Off-tree (in tests) there is no tween, so `deal_in()` must leave the cards already at rest.

- [ ] **Step 1: Write the failing test**

Create `tests/suites/test_hand_deal.gd`:

```gdscript
extends RefCounted

const TestRunner := preload("res://tests/run_tests.gd")

func run(t: TestRunner) -> void:
	_test_deal_leaves_every_card_at_rest(t)
	_test_deal_is_safe_for_an_empty_hand(t)

func _hand_with(ids: Array) -> HandView:
	var battle := BattleState.new(12345)
	battle.start()
	var hand: Array[CardData] = []
	for card_id: StringName in ids:
		hand.append(CardLibrary.load_card(card_id))
	battle.deck.hand = hand
	var view := HandView.new()
	view.rebuild(battle)
	return view

func _test_deal_leaves_every_card_at_rest(t: TestRunner) -> void:
	# The stagger animates cards in from below. If it left any card short of
	# its slot, the fan would be silently wrong.
	var view: HandView = _hand_with([&"jab", &"straight", &"jab", &"block", &"straight"])
	view.deal_in()
	var all_at_rest: bool = true
	for child: Node in view.get_children():
		var card: CardView = child as CardView
		if card == null:
			continue
		if card.target_position != card.rest_position:
			all_at_rest = false
	t.check(all_at_rest, "every card ends the deal at exactly its rest position")
	t.check_eq(view.get_child_count(), 5, "dealing does not add or drop cards")
	view.free()

func _test_deal_is_safe_for_an_empty_hand(t: TestRunner) -> void:
	var view: HandView = _hand_with([])
	view.deal_in()
	t.check_eq(view.get_child_count(), 0, "dealing an empty hand is safe")
	view.free()
```

- [ ] **Step 2: Run to verify it fails**

Run: `./tests/run_tests.sh`
Expected: FAIL — `Invalid call. Nonexistent function 'deal_in'`.

- [ ] **Step 3: Add the staggered deal**

In `scripts/ui/hand_view.gd`, call it at the end of `rebuild()`, after `refresh_states(battle)`:

```gdscript
	deal_in()
```

And add:

```gdscript
## Flies the hand in from below, one card at a time, so a new hand arrives
## rather than appearing. Each card springs from DEAL_FROM_BELOW up into its
## slot, staggered by DEAL_STAGGER.
##
## Off-tree (in tests) there is no tween, so the cards are simply left at rest —
## the invariant either way is that every card ends at its rest position.
func deal_in() -> void:
	if not is_inside_tree():
		return
	for index: int in range(get_child_count()):
		var view: CardView = get_child(index) as CardView
		if view == null:
			continue
		var landed: Vector2 = view.rest_position
		view.target_position = landed + Vector2(0.0, Juice.DEAL_FROM_BELOW)
		view.position = view.target_position
		var tween := Juice.spring(create_tween())
		tween.tween_interval(index * Juice.DEAL_STAGGER)
		tween.tween_property(view, "target_position", landed, Juice.SPRING_TIME)
```

- [ ] **Step 4: Run to verify it passes**

Run: `./tests/run_tests.sh`
Expected: PASS, 0 failures, count risen by 3. `test_hand_arc.gd`, `test_hand_play.gd` and `test_card_view.gd` must all still pass untouched.

- [ ] **Step 5: Commit**

```bash
git add -A
git commit -m "feat: deal the hand in from below, staggered"
```

---

### Task 6: FighterPanel — tumbling numbers, flash, impact burst

**Files:**
- Modify: `scripts/ui/fighter_panel.gd`

**Interfaces:**
- Consumes: `Juice`, `ParticleBurst`.
- Produces: no new public API. `shake_amplitude(amount: int) -> float` **stays** as a static but now delegates to `Juice.rect_shake_amplitude`, so `test_fighter_panel.gd`'s existing assertions keep passing unchanged.
- `PUNCH_SCALE`, `PUNCH_TIME`, `FLOAT_RISE`, `FLOAT_TIME`, `SHAKE_TIME`, `SHAKE_STEPS`, `FLOAT_HEIGHT` and the rect-shake constants move to `Juice`; the local copies are deleted. `PANEL_SIZE`, `RECT_SIZE`, `DAMAGE_FLASH`, `GUARD_FLASH`, `STATUS_COLOR` stay.

- [ ] **Step 1: Delegate the shake formula and drop the duplicated constants**

Replace `FighterPanel.shake_amplitude` with a delegation, so there is exactly one rect-shake formula in the project:

```gdscript
## Delegates to Juice so every tuning value lives in one file. Kept as a static
## on FighterPanel because tests and callers already reference it here.
static func shake_amplitude(amount: int) -> float:
	return Juice.rect_shake_amplitude(amount)
```

Delete the local `PUNCH_SCALE`, `PUNCH_TIME`, `FLOAT_RISE`, `FLOAT_TIME`, `SHAKE_TIME`, `SHAKE_STEPS`, `FLOAT_HEIGHT` and any rect-shake constants, and replace every use with the `Juice.` equivalent. `Juice.NUMBER_TIME` replaces `FLOAT_TIME`, `Juice.NUMBER_RISE` replaces `FLOAT_RISE`.

- [ ] **Step 2: Make the damage number tumble**

Replace `_float_number` so the number arcs sideways and spins as it rises, instead of drifting straight up:

```gdscript
## A damage number that arcs and tumbles rather than drifting straight up —
## motion with a direction reads as thrown, not faded.
func _float_number(text: String, colour: Color) -> void:
	var floater := Label.new()
	floater.text = text
	floater.add_theme_font_size_override("font_size", 22)
	floater.modulate = colour
	floater.position = _hp_label.position - Vector2(0.0, Juice.NUMBER_RISE * 0.4)
	floater.size = Vector2(PANEL_SIZE.x, 28.0)
	floater.horizontal_alignment = HORIZONTAL_ALIGNMENT_RIGHT if align_right else HORIZONTAL_ALIGNMENT_LEFT
	floater.mouse_filter = Control.MOUSE_FILTER_IGNORE
	floater.pivot_offset = floater.size / 2.0
	add_child(floater)

	# Arc away from the fighter's own side, so the two panels throw numbers
	# outward rather than both drifting the same way.
	var arc_x: float = Juice.NUMBER_ARC_X if align_right else -Juice.NUMBER_ARC_X
	var landing: Vector2 = floater.position + Vector2(arc_x, -Juice.NUMBER_RISE)

	var tween := create_tween()
	tween.tween_property(floater, "position", landing, Juice.NUMBER_TIME) \
		.set_trans(Tween.TRANS_QUAD).set_ease(Tween.EASE_OUT)
	tween.parallel().tween_property(floater, "rotation",
		deg_to_rad(Juice.NUMBER_SPIN_DEG if align_right else -Juice.NUMBER_SPIN_DEG),
		Juice.NUMBER_TIME)
	tween.parallel().tween_property(floater, "modulate:a", 0.0, Juice.NUMBER_TIME)
	tween.chain().tween_callback(floater.queue_free)
```

- [ ] **Step 3: Flash the rect and spawn an impact burst**

Add to `_pulse_damage`, after the existing punch/float/shake calls:

```gdscript
	_flash_rect(DAMAGE_FLASH)
	ParticleBurst.spawn(self, _rect_home + RECT_SIZE / 2.0, DAMAGE_FLASH, Juice.PARTICLES_HIT)
```

And add:

```gdscript
## Hard flash on the struck fighter's rectangle, then back to its own colour.
func _flash_rect(colour: Color) -> void:
	if not is_inside_tree():
		return
	var home: Color = _rect.color
	var tween := create_tween()
	tween.tween_property(_rect, "color", colour, Juice.FLASH_TIME * 0.35)
	tween.tween_property(_rect, "color", home, Juice.FLASH_TIME)
```

- [ ] **Step 4: Run to verify nothing regressed**

Run: `./tests/run_tests.sh`
Expected: PASS, 0 failures, count unchanged from Task 5. This task adds no tests; `test_fighter_panel.gd` is the regression guard, and its `shake_amplitude` assertions must still hold via the delegation.

- [ ] **Step 5: Commit**

```bash
git add -A
git commit -m "feat: tumbling damage numbers, rect flash and impact particles"
```

---

### Task 7: Wire ScreenFx and enlarge the window

**Files:**
- Modify: `scripts/ui/battle_view.gd`
- Modify: `project.godot`

**Interfaces:**
- Consumes: `ScreenFx` (`bind`, `hit_stop`, `shake`, `flash`), `Juice` (`screen_shake_amplitude`), `BattleHud`, `HandView`.
- Produces: no new public API.

- [ ] **Step 1: Enlarge the window**

In `project.godot`, under `[display]`, change:

```
window/size/window_width_override=2560
window/size/window_height_override=1440
```

Leave `viewport_width=1152`, `viewport_height=648` and the stretch settings alone — the design space is unchanged, so everything simply scales 2.22× instead of 1.67×. Both are 16:9, so `keep` still gives no letterboxing.

- [ ] **Step 2: Create and bind ScreenFx**

In `_build_ui`, after the HUD and hand are built and before `hud.bring_result_panel_to_front()`:

```gdscript
	screen_fx = ScreenFx.new()
	add_child(screen_fx)
	# The CanvasLayer is what shake offsets; the HUD is a Control, so the
	# full-screen flash can anchor to it.
	screen_fx.bind(layer, hud)
```

And declare it beside the other view members:

```gdscript
var screen_fx: ScreenFx
```

- [ ] **Step 3: Trigger hit-stop, shake and flash on damage**

`fighters_changed` carries no payload, and `FighterPanel` already derives the damage amount by diffing. Read it from there rather than changing anything in `scripts/core/`.

Replace `_on_fighters_changed`:

```gdscript
func _on_fighters_changed() -> void:
	hud.update_fighters(battle)
	hand_view.refresh_states(battle)
	_react_to_damage()

## FighterPanel diffs hp/guard itself and records what it saw, so the whole-view
## reaction can be driven from that without BattleState needing a payload.
func _react_to_damage() -> void:
	var amount: int = hud.last_damage_amount()
	if amount <= 0:
		return
	screen_fx.hit_stop()
	screen_fx.shake(Juice.screen_shake_amplitude(amount))
	screen_fx.flash()
```

This needs one accessor on `BattleHud` — add it there:

```gdscript
## The larger of the two panels' most recent damage pulses, or 0 if neither
## took damage. Lets the view react to a hit without BattleState carrying a
## damage payload.
func last_damage_amount() -> int:
	var player_hit: int = _player_panel.debug_last_pulse_amount if _player_panel.debug_last_pulse_kind == &"damage" else 0
	var enemy_hit: int = _enemy_panel.debug_last_pulse_amount if _enemy_panel.debug_last_pulse_kind == &"damage" else 0
	return maxi(player_hit, enemy_hit)
```

- [ ] **Step 4: Run the suite**

Run: `./tests/run_tests.sh`
Expected: PASS, 0 failures, count unchanged from Task 6.

- [ ] **Step 5: Smoke-test the real scene headlessly**

macOS has no `timeout(1)`; if a compound command is rejected as too complex, put it in a small wrapper script.

```bash
GODOT="/Users/mihai/Godot games/Godot.app/Contents/MacOS/Godot"
perl -e 'alarm 15; exec @ARGV' -- "$GODOT" --headless --path . 2>&1 | tee /tmp/juice-boot.log
grep -nE "SCRIPT ERROR|Parse Error|Invalid call|ERROR:" /tmp/juice-boot.log || echo "CLEAN"
```

The alarm killing the run is expected. A clean log means every node built and every signal connected.

- [ ] **Step 6: Verify the window size and that time scale is left normal**

Write a throwaway script (delete it; do not commit) that loads `res://level.tscn`, waits ~8 frames, plays a card through `hand_view.card_chosen.emit(0)`, waits ~30 frames, and prints:
- `DisplayServer.window_get_size()` — must be `(2560, 1440)`
- `root.get_visible_rect().size` — must be `(1152, 648)`
- `Engine.time_scale` — **must be back to `1.0`** after the hit-stop has elapsed
- the `CanvasLayer.offset` — **must be back to its home** after the shake

The last two are the catastrophic failure modes. Report the actual printed values.

- [ ] **Step 7: Commit**

```bash
git add -A
git commit -m "feat: wire screen shake, hit stop and flash; window to 2560x1440"
```

---

### Task 8: Contact-sheet tool and visual tuning

**Files:**
- Create: `tools/capture_frames.gd`

**Interfaces:**
- Consumes: the finished game.
- Produces: a command-line tool that renders a tiled contact sheet of consecutive frames, so animation curves can be judged from a still image.

**Why this exists:** a single screenshot cannot show whether motion overshoots and settles, slides linearly, or wobbles too long. Tiling consecutive frames makes the curve visible, which is the only way to tune easing without feeling it live.

- [ ] **Step 1: Write the tool**

Create `tools/capture_frames.gd`:

```gdscript
extends SceneTree

## Renders a tiled contact sheet of consecutive frames so animation curves can
## be judged from a still image. A single screenshot cannot show whether motion
## overshoots and settles or slides linearly; a strip of frames can.
##
## Run NON-headless (a rendering context is required):
##   "$GODOT" --path . --script res://tools/capture_frames.gd
##
## Writes /tmp/juice-sheet-<name>.png per captured sequence.

const COLUMNS: int = 4
const ROWS: int = 3
const FRAME_STRIDE: int = 2

func _initialize() -> void:
	_run.call_deferred()

func _run() -> void:
	var scene: Node = load("res://level.tscn").instantiate()
	root.add_child(scene)
	for _i: int in range(10):
		await process_frame

	await _capture("hover", func() -> void:
		var card: CardView = scene.hand_view.get_child(2) as CardView
		card.apply_hover(true))

	await _capture("play", func() -> void:
		scene.hand_view.card_chosen.emit(0))

	print("contact sheets written to /tmp/juice-sheet-*.png")
	quit(0)

## Fires `trigger`, then captures COLUMNS*ROWS frames every FRAME_STRIDE frames
## and tiles them into one image.
func _capture(name: String, trigger: Callable) -> void:
	var shots: Array[Image] = []
	trigger.call()
	for i: int in range(COLUMNS * ROWS):
		for _s: int in range(FRAME_STRIDE):
			await process_frame
		shots.append(root.get_texture().get_image())

	var cell: Vector2i = shots[0].get_size()
	var sheet := Image.create(cell.x * COLUMNS, cell.y * ROWS, false, shots[0].get_format())
	for i: int in range(shots.size()):
		var col: int = i % COLUMNS
		var row: int = i / COLUMNS
		sheet.blit_rect(shots[i], Rect2i(Vector2i.ZERO, cell),
			Vector2i(col * cell.x, row * cell.y))
	sheet.save_png("/tmp/juice-sheet-%s.png" % name)
	print("  wrote /tmp/juice-sheet-%s.png (%d frames)" % [name, shots.size()])
```

- [ ] **Step 2: Run it**

```bash
GODOT="/Users/mihai/Godot games/Godot.app/Contents/MacOS/Godot"
perl -e 'alarm 90; exec @ARGV' -- "$GODOT" --path . --script res://tools/capture_frames.gd 2>&1 | tail -5
ls -l /tmp/juice-sheet-*.png
```

Expected: two PNGs, each a 4×3 grid of frames.

- [ ] **Step 3: Judge the curves and report**

Look at both sheets and report, honestly, for each:
- Does the hover lift **overshoot and settle**, or slide linearly into place?
- Does the played card show a visible **backswing** before it travels?
- Does anything **wobble for too long** — still visibly moving in the last frames?
- Is the motion legible, or does it read as noise?

If a curve looks wrong, say which `Juice` constant you would change and why, but **do not change it** — tuning is the user's call to make while playing. Report the observation.

- [ ] **Step 4: Also capture the resting and hit states**

Take two ordinary single screenshots (throwaway script, delete it, do not commit) at `/tmp/juice-rest.png` and `/tmp/juice-hit.png`: the resting fan, and the frame just after a hit with particles and a floating number visible. Report what you see, including whether the particles are visible and whether the screen shake has visibly displaced the view.

- [ ] **Step 5: Commit**

```bash
git add -A
git commit -m "tools: add frame contact-sheet capture for judging animation curves"
```

---

## Self-Review

**Spec coverage.** Resolution → Task 7; composition layer → Task 3; `juice.gd` as sole tuning surface → Task 1, with Tasks 3 and 6 deleting their local duplicates; hit-stop + watchdog → Task 2; screen shake self-correction → Task 2; flash → Tasks 2 (screen) and 6 (rect); spring easing → Task 1 helper, applied in Tasks 3 and 5; squash/stretch → Task 3; anticipation → Task 3; cursor tilt → Task 3; idle sway → Task 3; staggered deal → Task 5; tumbling numbers → Task 6; particles → Tasks 4 and 6; readability mitigation (hover pauses idle) → Task 3, asserted; contact-sheet validation → Task 8. Spec tests 1–10 map to Tasks 1 (1–3, 7), 2 (4–6), 4 (9), 5 (8), with test 10 (the 344 baseline) checked at every task's verify step.

**Placeholder scan.** No TBD/TODO, no "add error handling", no "similar to Task N". Every code step carries complete code.

**Type consistency.** `compose_position`/`compose_rotation` are defined in Task 1 and called in Task 3. `screen_shake_amplitude` (Task 1) is called in Task 7; `rect_shake_amplitude` (Task 1) is delegated to in Task 6. `ScreenFx.bind(layer, overlay_parent)` is two-argument in Task 2's definition and Task 7's call. `ParticleBurst.spawn(parent, at, colour, count)` matches between Tasks 4 and 6. `deal_in()` is named identically in Task 5's definition, its call site in `rebuild()`, and its test. `last_damage_amount()` is added to `BattleHud` in Task 7 Step 3 and consumed in the same step. `debug_last_pulse_kind`/`debug_last_pulse_amount` already exist on `FighterPanel` from the prior pass.

**Two deliberate deviations from the spec's test list.** (a) The spec asks for a test that hovering zeroes idle; Task 3 asserts `debug_idle_offset() == Vector2.ZERO` while hovered, which is that guarantee. (b) The spec's "shake returns to home" test runs detached, where no tween exists — so it asserts the offset is *untouched* at home, and Task 7 Step 6 verifies the in-tree return-to-home on the real scene. Asserting a tween's endpoint without frames is not possible; splitting it this way tests both halves honestly.

**Known risk carried from the spec.** `Engine.time_scale` is global, and Task 2's test mutates it. The test restores it unconditionally at the end of both affected functions, including after a failed assertion, so a failure cannot leave other suites running in slow motion.
